Add ability to preserve your directory structure in the output.
imagemin/imagemin pull request #353
Opened 2020-04-29 23:24 UTC by gijsroge

W.I.P.

Fixes #191

If the `preserveDirectories` is set the output will match the directory structure from the input. 

Another possibility would be to introduce a breaking change and make this de default behaviour as that's what I would expect, but maybe this is a more safe route.

Example:

Given: `assets/images/1.jpg, assets/images/nested/2.svg, assets/images/nested/nested/3.gif`

``` javascript
imagemin(['assets/images/**/*.{jpg,svg,gif}'], {
	plugins: [imageminJpegtran(), imageminWebp(), imageminSvgo()],
	destination: 'dest',
	preserveDirectories: true
});
```

Our output would be `dest/assets/images/1.jpg, dest/assets/images/nested/assets/2.svg, dest/images/nested/nested/3.gif`

cc/ #293 #262 #225 #213 #196 #192

2020-04-29 23:56 UTC, gijsroge commented
Still working out some use cases I didn't cover.

2020-04-30 01:13 UTC, gijsroge commented on index.js
> +const handleFile = async (sourcePath, base, {destination, preserveDirectories, plugins = []}) => {
If a user has a glob like this `assets/images/**/*.{jpg,svg,webp}` we need the base in order to copy all the files in the destination without the `assets/images/` directory/

2020-06-17 12:07 UTC, rolbr commented
@gijsroge 
Sweet, exactly what I was looking for! 🥳

However, I encountered a bug that would *not* preserve directory structure for the first subdirectory.

Script:
```
(async () => {
	const files = await imagemin(['input_dir/**/*.{jpg,jpeg,png,svg}'], {
		destination: 'output_dir',
		preserveDirectories: true,
		...
```

Files/ directories:
```
⨽ input_dir
   ⊢ sub_dir_1
   ∣  ⨽ files 1…N
   ⨽ sub_dir_2
      ⨽ files 1…N
```
All files in `input_dir/sub_dir_1` would be written to `output_dir/` whereas  
files in `input_dir/sub_dir_2` would be written to `output_dir/sub_dir_2`.

Is this something you can reproduce?

2020-07-20 18:59 UTC, glassdimlygr commented
I can verify this bug:
```
  {
    data: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff ed 01 6e 50 68 6f 74 6f 73 68 6f 70 20 33 2e 30 00 38 42 49 4d 04 04 00 00 00 00 01 52 ... 648764 more bytes>,
    sourcePath: '/root/image_resize/img_s3/subdir/9c2e10e4-efc1-4cb3-aaa5-3582ed5a1aa7_GettyImages-1037487390.jpg',
    destinationPath: '/root/image_resize/img_s3/9c2e10e4-efc1-4cb3-aaa5-3582ed5a1aa7_GettyImages-1037487390.jpg'
  }
```

2020-07-21 10:43 UTC, yuceltoluyag commented
ty  save my life <3 @gijsroge

2020-08-10 20:55 UTC, sindresorhus commented on index.js
> +		returnValue.destinationPath = path.join(path.dirname(destinationPath), sourcePath.replace(baseDirectory, ''));
I don't think using `.replace` will work cross-platform. Use the `path` related methods for path manipulation.

2020-08-10 20:56 UTC, sindresorhus commented on index.js
> +	const baseDirectory = path.dirname(filePaths[0]);
Why does the first file path decide the base directory? This should be documented.

2020-08-10 20:56 UTC, sindresorhus commented on readme.md
> +If enabled the directory structure from the input is preserved.
```suggestion
Preserve the source directory structure in the output.
```

2020-08-10 20:56 UTC, sindresorhus commented on test.js
> +test('Preserve directory structure', async t => {
```suggestion
test('preserve directory structure', async t => {
```

2020-09-29 06:12 UTC, yellow1912 commented
What is the status with this PR? Can we have it merged soon?

2020-09-29 10:54 UTC, gijsroge commented
@yellow1912 i'm picking this back up in the next few days.

2021-03-07 07:00 UTC, misaka00251 commented
Hey, just asking..What's the status of this PR?

2021-03-07 21:52 UTC, illycz commented
Any news about PR?

2021-04-29 09:52 UTC, kosssi commented
This feature is essential 🎉

I used this command pending this:
```
find ./static -type f | xargs -I % sh -c 'imagemin % -o $(dirname %)'
```

Thanks for imagemin :+1:

2021-06-03 04:31 UTC, leesei commented
I've implemented something similar locally.

Concerning @sindresorhus's question on "Why does the first file path decide the base directory? This should be documented.", how about we only enable `preserveDirectories` for glob inputs?
Then we rather than passing `baseDirectory`, we just need to:

```js
let destinationPath = destination ? path.join(destination, preserveDirectories? sourcePath: path.basename(sourcePath)) : undefined;
```

2021-11-10 08:43 UTC, sindresorhus requested changes

2021-11-10 08:43 UTC, sindresorhus commented on index.js
> +		returnValue.destinationPath = path.join(destination, path.parse(sourcePath).dir.replace(basePath, ''), path.basename(destinationPath));
Use `path.dirname`

2021-11-10 08:43 UTC, sindresorhus commented on readme.md
> +- `assets/images/1.jpg` -> `dist/1.jpg`
```suggestion
- `assets/images/1.jpg` → `dist/1.jpg`
```

2021-11-10 08:43 UTC, sindresorhus commented
Tests are failing on Windows.

2021-11-23 15:07 UTC, pumano commented
@gijsroge thank you for that very important feature! Hope it will be merged soon!

2022-03-25 17:43 UTC, eBaeza commented
Very important feature! Hope it will be merged soon!

2022-04-02 20:16 UTC, rtatarinov commented
Any updates about it?

2022-07-28 04:44 UTC, ChanhyukPark-Tech commented
Very important feature! Hope it will be merged soon!!!

2022-11-14 14:07 UTC, lewis-dbi commented
is this not being worked on anymore?

2023-03-07 16:32 UTC, Shayan-To commented
Any progress? This is really necessary.

2023-03-07 22:39 UTC, tofran commented
@Shayan-To @eBaeza, @rtatarinov, etc

Please refrain from making such comments. There are plenty of people subscribed to threads and this kind of comment just spams their inbox. Please only comment if you have something to add to the discussion.

If this is so "*necessary*" feel free to contribute with valuable help. This might even include making a PR to the fork, helping the original author.

Thank you.

2023-05-05 18:32 UTC, Xmetalfanx commented
any update on this or a usable fork of imagemin since this seems like its no longer maintained (i mean the repo SAYS unmaintained) .... I am switching to this from using imagemin in gulp and i just ran across this issue.

also thank you to the community member(s?) working on a fix even if PRs aren't getting merged

2023-08-03 15:07 UTC, saeidzebardast commented
Any progress on this?

2024-04-29 05:59 UTC, sindresorhus commented
Closing for lack of activity from OP.

2024-04-29 05:59 UTC, closed without merging